spring:
  profiles:
    active: dev
blogus:
  host: http://localhost:8080
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/blogus
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
token:
  secret: ykIQjX6bZSHO0mkjkNL8U3Ht9NtzjtIZ

---
spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    hikari:
      connection-test-query: SELECT 1
    username: sa
    password:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true